--DEPRECATED

CREATE TABLE HELPREQUEST (
	REQUESTID INT NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	EMAILADDRESS VARCHAR(50),
	PHONENUMBER VARCHAR(10),
	URGENT BIT,
	COMMENTS TEXT,
	DATEENTERED DATE,
	STATUS_ID INT,
	TECHNICIAN_ID INT,
	ROOMNUMBER VARCHAR(10) NOT NULL,
	LOCATION_ID INT NOT NULL,
	ISSUE_ID INT NOT NULL,
	PRIMARY KEY (REQUESTID)
);

